-- GENERATED BY AI (2026-02-26) --
USE tp4d5;
GO

/* =========================
   PARUTIONS (jusqu'à Year Zero)
   ========================= */

INSERT INTO nine_inch_nails.Parution (Nom, TypeParution, DateSortie, NbVente, NbPiste)
VALUES
('Down in It', 'single', '1989-09-15', 100000, 1),
('Pretty Hate Machine', 'album', '1989-10-20', 3000000, 10),
('Broken', 'ep', '1992-09-22', 1000000, 8),
('The Downward Spiral', 'album', '1994-03-08', 4000000, 14),
('The Perfect Drug', 'single', '1997-09-22', 200000, 1),
('The Fragile', 'album', '1999-09-21', 900000, 23),
('With Teeth', 'album', '2005-05-03', 1400000, 13),
('Year Zero', 'album', '2007-04-17', 800000, 16);
GO


/* =========================
   PISTES
   ========================= */

INSERT INTO nine_inch_nails.Piste (Nom, TypePiste, DureeSec, EstInstrumentale, AGagneGrammy)
VALUES

/* Pretty Hate Machine */
('Head Like a Hole','originale',299,0,0),
('Terrible Lie','originale',278,0,0),
('Down in It','originale',226,0,0),
('Sanctified','originale',311,0,0),
('Something I Can Never Have','originale',357,0,0),
('Kinda I Want To','originale',273,0,0),
('Sin','originale',276,0,0),
('That''s What I Get','originale',270,0,0),
('The Only Time','originale',289,0,0),
('Ringfinger','originale',342,0,0),

/* Broken */
('Pinion','originale',78,1,0),
('Wish','originale',226,0,1),
('Last','originale',268,0,0),
('Help Me I Am in Hell','originale',102,1,0),
('Happiness in Slavery','originale',314,0,1),
('Gave Up','originale',271,0,0),

/* The Downward Spiral */
('Mr. Self Destruct','originale',270,0,0),
('Piggy','originale',281,0,0),
('Heresy','originale',294,0,0),
('March of the Pigs','originale',178,0,0),
('Closer','originale',373,0,0),
('Ruiner','originale',298,0,0),
('The Becoming','originale',331,0,0),
('I Do Not Want This','originale',321,0,0),
('Big Man with a Gun','originale',96,0,0),
('A Warm Place','originale',203,1,0),
('Eraser','originale',413,0,0),
('Reptile','originale',403,0,0),
('The Downward Spiral','originale',254,0,0),
('Hurt','originale',373,0,0),

/* The Perfect Drug */
('The Perfect Drug','originale',495,0,0),

/* The Fragile (principales 23 pistes album standard) */
('Somewhat Damaged','originale',271,0,0),
('The Day the World Went Away','originale',275,0,0),
('The Frail','originale',114,1,0),
('The Wretched','originale',311,0,0),
('We''re in This Together','originale',441,0,0),
('The Fragile','originale',275,0,0),
('Just Like You Imagined','originale',229,1,0),
('Even Deeper','originale',310,0,0),
('Pilgrimage','originale',229,0,0),
('No, You Don''t','originale',216,0,0),
('La Mer','originale',274,1,0),
('The Great Below','originale',317,0,0),
('The Way Out Is Through','originale',257,0,0),
('Into the Void','originale',289,0,0),
('Where Is Everybody?','originale',323,0,0),
('The Mark Has Been Made','originale',331,1,0),
('Please','originale',231,0,0),
('Starfuckers, Inc.','originale',300,0,0),
('Complication','originale',140,1,0),
('I''m Looking Forward to Joining You, Finally','originale',260,0,0),
('The Big Come Down','originale',270,0,0),
('Underneath It All','originale',460,0,0),
('Ripe (With Decay)','originale',413,0,0),

/* With Teeth */
('All the Love in the World','originale',254,0,0),
('You Know What You Are?','originale',221,0,0),
('The Collector','originale',186,0,0),
('The Hand That Feeds','originale',211,0,0),
('Love Is Not Enough','originale',228,0,0),
('Every Day Is Exactly the Same','originale',295,0,0),
('With Teeth','originale',337,0,0),
('Only','originale',263,0,0),
('Getting Smaller','originale',223,0,0),
('Sunspots','originale',183,0,0),
('The Line Begins to Blur','originale',223,0,0),
('Beside You in Time','originale',333,0,0),
('Right Where It Belongs','originale',306,0,0),

/* Year Zero */
('Hyperpower!','originale',105,1,0),
('The Beginning of the End','originale',193,0,0),
('Survivalism','originale',263,0,0),
('The Good Soldier','originale',220,0,0),
('Vessel','originale',233,0,0),
('Me, I''m Not','originale',250,0,0),
('Capital G','originale',232,0,0),
('My Violent Heart','originale',294,0,0),
('The Warning','originale',227,0,0),
('God Given','originale',214,0,0),
('Meet Your Master','originale',221,0,0),
('The Greater Good','originale',279,0,0),
('The Great Destroyer','originale',263,0,0),
('Another Version of the Truth','originale',283,1,0),
('In This Twilight','originale',321,0,0),
('Zero-Sum','originale',338,0,0);
GO

INSERT INTO nine_inch_nails.PisteParution (PisteId, ParutionId)
SELECT p.PisteId, pa.ParutionId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Parution pa ON pa.Nom = 'Down in It'
WHERE p.Nom = 'Down in It';

INSERT INTO nine_inch_nails.PisteParution (PisteId, ParutionId)
SELECT p.PisteId, pa.ParutionId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Parution pa ON pa.Nom = 'Pretty Hate Machine'
WHERE p.Nom IN (
'Head Like a Hole','Terrible Lie','Down in It','Sanctified',
'Something I Can Never Have','Kinda I Want To','Sin',
'That''s What I Get','The Only Time','Ringfinger'
);

INSERT INTO nine_inch_nails.PisteParution (PisteId, ParutionId)
SELECT p.PisteId, pa.ParutionId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Parution pa ON pa.Nom = 'Broken'
WHERE p.Nom IN (
'Pinion','Wish','Last','Help Me I Am in Hell',
'Happiness in Slavery','Gave Up'
);

INSERT INTO nine_inch_nails.PisteParution (PisteId, ParutionId)
SELECT p.PisteId, pa.ParutionId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Parution pa ON pa.Nom = 'The Downward Spiral'
WHERE p.Nom IN (
'Mr. Self Destruct','Piggy','Heresy','March of the Pigs','Closer',
'Ruiner','The Becoming','I Do Not Want This','Big Man with a Gun',
'A Warm Place','Eraser','Reptile','The Downward Spiral','Hurt'
);

INSERT INTO nine_inch_nails.PisteParution (PisteId, ParutionId)
SELECT p.PisteId, pa.ParutionId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Parution pa ON pa.Nom = 'The Perfect Drug'
WHERE p.Nom = 'The Perfect Drug';

INSERT INTO nine_inch_nails.PisteParution (PisteId, ParutionId)
SELECT p.PisteId, pa.ParutionId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Parution pa ON pa.Nom = 'The Fragile'
WHERE p.Nom IN (
'Somewhat Damaged','The Day the World Went Away','The Frail','The Wretched',
'We''re in This Together','The Fragile','Just Like You Imagined',
'Even Deeper','Pilgrimage','No, You Don''t','La Mer','The Great Below',
'The Way Out Is Through','Into the Void','Where Is Everybody?',
'The Mark Has Been Made','Please','Starfuckers, Inc.','Complication',
'I''m Looking Forward to Joining You, Finally','The Big Come Down',
'Underneath It All','Ripe (With Decay)'
);

INSERT INTO nine_inch_nails.PisteParution (PisteId, ParutionId)
SELECT p.PisteId, pa.ParutionId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Parution pa ON pa.Nom = 'With Teeth'
WHERE p.Nom IN (
'All the Love in the World','You Know What You Are?','The Collector',
'The Hand That Feeds','Love Is Not Enough',
'Every Day Is Exactly the Same','With Teeth','Only','Getting Smaller',
'Sunspots','The Line Begins to Blur','Beside You in Time',
'Right Where It Belongs'
);

INSERT INTO nine_inch_nails.PisteParution (PisteId, ParutionId)
SELECT p.PisteId, pa.ParutionId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Parution pa ON pa.Nom = 'Year Zero'
WHERE p.Nom IN (
'Hyperpower!','The Beginning of the End','Survivalism','The Good Soldier',
'Vessel','Me, I''m Not','Capital G','My Violent Heart',
'The Warning','God Given','Meet Your Master','The Greater Good',
'The Great Destroyer','Another Version of the Truth',
'In This Twilight','Zero-Sum'
);

INSERT INTO nine_inch_nails.Tournee (NomOfficiel, AnneeDebut, AnneeFin)
VALUES
('Pretty Hate Machine Tour', 1988, 1991),
('Self Destruct Tour', 1994, 1996),
('Fragility Tour', 1999, 2000),
('Live: With Teeth Tour', 2005, 2006),
('Performance 2007 Tour', 2007, 2007);

INSERT INTO nine_inch_nails.PisteTournee (PisteId, TourneeId)
SELECT p.PisteId, t.TourneeId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Tournee t ON t.NomOfficiel = 'Self Destruct Tour'
WHERE p.Nom IN ('Closer','Hurt','March of the Pigs','Wish');

INSERT INTO nine_inch_nails.PisteTournee (PisteId, TourneeId)
SELECT p.PisteId, t.TourneeId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Tournee t ON t.NomOfficiel = 'Fragility Tour'
WHERE p.Nom IN ('The Day the World Went Away','We''re in This Together','Hurt');

INSERT INTO nine_inch_nails.PisteTournee (PisteId, TourneeId)
SELECT p.PisteId, t.TourneeId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Tournee t ON t.NomOfficiel = 'Live: With Teeth Tour'
WHERE p.Nom IN ('The Hand That Feeds','Only','Every Day Is Exactly the Same');

INSERT INTO nine_inch_nails.PisteTournee (PisteId, TourneeId)
SELECT p.PisteId, t.TourneeId
FROM nine_inch_nails.Piste p
JOIN nine_inch_nails.Tournee t ON t.NomOfficiel = 'Performance 2007 Tour'
WHERE p.Nom IN ('Survivalism','Capital G','The Beginning of the End');

INSERT INTO nine_inch_nails.Videoclip (NomOfficiel, DateSortie, PisteId)
SELECT 'Head Like a Hole','1989-01-01',PisteId
FROM nine_inch_nails.Piste WHERE Nom='Head Like a Hole';

INSERT INTO nine_inch_nails.Videoclip (NomOfficiel, DateSortie, PisteId)
SELECT 'Wish','1992-01-01',PisteId
FROM nine_inch_nails.Piste WHERE Nom='Wish';

INSERT INTO nine_inch_nails.Videoclip (NomOfficiel, DateSortie, PisteId)
SELECT 'Closer','1994-05-10',PisteId
FROM nine_inch_nails.Piste WHERE Nom='Closer';

INSERT INTO nine_inch_nails.Videoclip (NomOfficiel, DateSortie, PisteId)
SELECT 'Hurt','1995-01-01',PisteId
FROM nine_inch_nails.Piste WHERE Nom='Hurt';

INSERT INTO nine_inch_nails.Videoclip (NomOfficiel, DateSortie, PisteId)
SELECT 'The Perfect Drug','1997-01-01',PisteId
FROM nine_inch_nails.Piste WHERE Nom='The Perfect Drug';

INSERT INTO nine_inch_nails.Videoclip (NomOfficiel, DateSortie, PisteId)
SELECT 'We''re in This Together','1999-01-01',PisteId
FROM nine_inch_nails.Piste WHERE Nom='We''re in This Together';

INSERT INTO nine_inch_nails.Videoclip (NomOfficiel, DateSortie, PisteId)
SELECT 'The Hand That Feeds','2005-01-01',PisteId
FROM nine_inch_nails.Piste WHERE Nom='The Hand That Feeds';

INSERT INTO nine_inch_nails.Videoclip (NomOfficiel, DateSortie, PisteId)
SELECT 'Only','2005-01-01',PisteId
FROM nine_inch_nails.Piste WHERE Nom='Only';

INSERT INTO nine_inch_nails.Videoclip (NomOfficiel, DateSortie, PisteId)
SELECT 'Survivalism','2007-01-01',PisteId
FROM nine_inch_nails.Piste WHERE Nom='Survivalism';
