-- GENERATED BY AI (2026-02-21) --
USE tp4d5;
GO

-- Insert Parution (Albums, EPs, Singles)
INSERT INTO nine_inch_nails.Parution (Nom, TypeParution, DateSortie, NbVente, NbPiste)
VALUES
	('Pretty Hate Machine', 'album', '1989-10-20', 1500000, 12),
	('Broken', 'album', '1992-09-22', 2000000, 8),
	('The Downward Spiral', 'album', '1994-03-22', 3000000, 13),
	('The Fragile', 'album', '1999-09-21', 2500000, 22),
	('With Teeth', 'album', '2005-05-03', 1800000, 13),
	('Year Zero', 'album', '2007-04-17', 900000, 18),
	('The Slip', 'album', '2008-05-05', 600000, 13),
	('Hesitation Marks', 'album', '2013-09-03', 700000, 13),
	('Bad Witch', 'album', '2018-06-22', 800000, 8),
	('Add Violence', 'ep', '2017-07-21', 300000, 5),
	('Further Down the Spiral', 'ep', '1995-03-22', 400000, 6),
	('Things Falling Apart', 'ep', '2000-12-12', 250000, 8);
GO

-- Insert Piste (Tracks)
INSERT INTO nine_inch_nails.Piste (Nom, TypePiste, DureeSec, AGagneGrammy)
VALUES
	('Head Like a Hole', 'originale', 291, 0),
	('Terrible Lie', 'originale', 289, 0),
	('Down in It', 'originale', 234, 0),
	('Broken', 'originale', 178, 1),
	('Gave Up', 'originale', 360, 1),
	('Pinion', 'originale', 93, 0),
	('Wish', 'originale', 164, 1),
	('Last', 'originale', 291, 0),
	('March of the Pigs', 'originale', 232, 0),
	('Closer', 'originale', 249, 1),
	('The Downward Spiral', 'originale', 282, 0),
	('I Do Not Want This', 'originale', 202, 0),
	('Big Come Down', 'originale', 272, 0),
	('The Perfect Girl', 'originale', 278, 0),
	('Heresy', 'originale', 246, 0),
	('Reptile', 'originale', 373, 0),
	('The Way Out Is Through', 'originale', 285, 0),
	('Into the Void', 'originale', 291, 0),
	('All That Could Have Been', 'originale', 347, 0),
	('Somewhat Damaged', 'originale', 284, 0),
	('The Big Come Down', 'originale', 272, 0),
	('Try to Erase Me', 'originale', 292, 0),
	('The Wretched', 'originale', 453, 0),
	('With Teeth', 'originale', 194, 0),
	('Love Is Not Enough', 'originale', 230, 0),
	('Every Day Is Exactly the Same', 'originale', 205, 0),
	('Only', 'originale', 196, 0),
	('Survivalism', 'originale', 213, 0),
	('Me, I''m Not', 'originale', 205, 0),
	('Capital G', 'originale', 242, 0),
	('The Good Soldier', 'originale', 227, 0),
	('The Slip', 'originale', 225, 0),
	('Letting Go', 'originale', 190, 0),
	('Echoplex', 'originale', 275, 0),
	('Yet Another Movie', 'originale', 192, 0),
	('All Time Low', 'originale', 229, 0),
	('The Wailing Wall', 'remix', 296, 0),
	('Reptile (Meat Beat Manifesto Mix)', 'remix', 368, 0),
	('I Don''t Want This', 'remix', 215, 0),
	('Copy of a', 'remix', 278, 0),
	('Beside You in Time', 'live', 385, 0),
	('Discipline', 'originale', 242, 0),
	('Come Back Haunted', 'originale', 243, 0),
	('Hurt', 'originale', 352, 1),
	('In This Twilight', 'originale', 279, 0),
	('Less Than', 'originale', 252, 0);
GO

-- Insert Tournee (Tours)
INSERT INTO nine_inch_nails.Tournee (NomOfficiel, AnneeDebut, AnneeFin)
VALUES
	('Pretty Hate Machine Tour', 1989, 1990),
	('Broken Tour', 1992, 1993),
	('Self Destruct Tour', 1994, 1995),
	('Against All Authority Tour', 1997, 1999),
	('Fragility Tour', 1999, 2000),
	('With Teeth Tour', 2005, 2006),
	('Year Zero Tour', 2007, 2008),
	('Lights in the Sky Tour', 2008, 2009),
	('Hesitation Marks Tour', 2013, 2014),
	('Bad Witch Tour', 2018, 2019);
GO

-- Insert PisteParution using subqueries to lookup PisteId by Nom
INSERT INTO nine_inch_nails.PisteParution (PisteId, ParutionId)
SELECT p.PisteId, pa.ParutionId
FROM (
	VALUES
		-- Pretty Hate Machine (ParutionId = 1)
		('Head Like a Hole', 1),
		('Terrible Lie', 1),
		('Down in It', 1),
		('With Teeth', 1),
		('Love Is Not Enough', 1),
		('Every Day Is Exactly the Same', 1),
		('Only', 1),
		('Survivalism', 1),
		('Me, I''m Not', 1),
		('Capital G', 1),
		('The Good Soldier', 1),
		('The Slip', 1),
		-- Broken (ParutionId = 2)
		('Broken', 2),
		('Gave Up', 2),
		('Pinion', 2),
		('Wish', 2),
		('Last', 2),
		('The Wailing Wall', 2),
		('Reptile (Meat Beat Manifesto Mix)', 2),
		('I Don''t Want This', 2),
		-- The Downward Spiral (ParutionId = 3)
		('March of the Pigs', 3),
		('Closer', 3),
		('The Downward Spiral', 3),
		('I Do Not Want This', 3),
		('Big Come Down', 3),
		('The Perfect Girl', 3),
		('Heresy', 3),
		('Reptile', 3),
		('The Way Out Is Through', 3),
		('Into the Void', 3),
		('All That Could Have Been', 3),
		('Somewhat Damaged', 3),
		('The Big Come Down', 3),
		-- The Fragile (ParutionId = 4)
		('Try to Erase Me', 4),
		('The Wretched', 4),
		('Echoplex', 4),
		('Yet Another Movie', 4),
		('All Time Low', 4),
		('Copy of a', 4),
		('Beside You in Time', 4),
		('Discipline', 4),
		('Come Back Haunted', 4),
		('Hurt', 4),
		('In This Twilight', 4),
		('Less Than', 4),
		-- With Teeth (ParutionId = 5)
		('With Teeth', 5),
		('Love Is Not Enough', 5),
		('Every Day Is Exactly the Same', 5),
		('Only', 5),
		('Survivalism', 5),
		('Me, I''m Not', 5),
		('Capital G', 5),
		('The Good Soldier', 5),
		('The Slip', 5),
		('Letting Go', 5),
		('Echoplex', 5),
		('Yet Another Movie', 5),
		('All Time Low', 5),
		-- Year Zero (ParutionId = 6)
		('Discipline', 6),
		('Come Back Haunted', 6),
		('Hurt', 6),
		('In This Twilight', 6),
		('Less Than', 6)
) AS vt(PisteName, ParutionId)
INNER JOIN nine_inch_nails.Piste p ON p.Nom = vt.PisteName
INNER JOIN nine_inch_nails.Parution pa ON pa.ParutionId = vt.ParutionId;
GO

-- Insert Videoclip using subqueries to lookup PisteId by Nom
INSERT INTO nine_inch_nails.Videoclip (NomOfficiel, DateSortie, PisteId)
SELECT vc.VideoclipName, vc.DateSortie, p.PisteId
FROM (
	VALUES
		('Head Like a Hole', '1989-11-15', 'Head Like a Hole'),
		('Terrible Lie', '1990-06-15', 'Terrible Lie'),
		('Down in It', '1994-03-01', 'Down in It'),
		('Broken', '1992-10-15', 'Broken'),
		('Gave Up', '1992-11-15', 'Gave Up'),
		('Wish', '1992-12-15', 'Wish'),
		('Closer', '1994-06-15', 'Closer'),
		('March of the Pigs', '1994-07-15', 'March of the Pigs'),
		('Hurt', '1994-11-15', 'Hurt'),
		('Perfect Girl', '1995-01-15', 'The Perfect Girl'),
		('The Big Come Down', '1997-09-15', 'The Big Come Down'),
		('Every Day Is Exactly the Same', '2005-06-15', 'Every Day Is Exactly the Same'),
		('Only', '2005-08-15', 'Only'),
		('Survivalism', '2007-10-15', 'Survivalism'),
		('Come Back Haunted', '2013-08-20', 'Come Back Haunted')
) AS vc(VideoclipName, DateSortie, PisteName)
INNER JOIN nine_inch_nails.Piste p ON p.Nom = vc.PisteName;
GO

-- Insert PisteTournee using subqueries to lookup IDs by names
INSERT INTO nine_inch_nails.PisteTournee (PisteId, TourneeId)
SELECT p.PisteId, t.TourneeId
FROM (
	VALUES
		-- Pretty Hate Machine Tour
		('Head Like a Hole', 'Pretty Hate Machine Tour'),
		('Terrible Lie', 'Pretty Hate Machine Tour'),
		('Down in It', 'Pretty Hate Machine Tour'),
		-- Broken Tour
		('Broken', 'Broken Tour'),
		('Gave Up', 'Broken Tour'),
		('Wish', 'Broken Tour'),
		('Last', 'Broken Tour'),
		-- Self Destruct Tour
		('March of the Pigs', 'Self Destruct Tour'),
		('Closer', 'Self Destruct Tour'),
		('The Downward Spiral', 'Self Destruct Tour'),
		('The Perfect Girl', 'Self Destruct Tour'),
		('Heresy', 'Self Destruct Tour'),
		-- Against All Authority Tour
		('March of the Pigs', 'Against All Authority Tour'),
		('Closer', 'Against All Authority Tour'),
		('The Downward Spiral', 'Against All Authority Tour'),
		('Try to Erase Me', 'Against All Authority Tour'),
		('The Wretched', 'Against All Authority Tour'),
		-- Fragility Tour
		('Try to Erase Me', 'Fragility Tour'),
		('The Wretched', 'Fragility Tour'),
		('Head Like a Hole', 'Fragility Tour'),
		('Hurt', 'Fragility Tour'),
		-- With Teeth Tour
		('With Teeth', 'With Teeth Tour'),
		('Love Is Not Enough', 'With Teeth Tour'),
		('Every Day Is Exactly the Same', 'With Teeth Tour'),
		('Only', 'With Teeth Tour'),
		('Hurt', 'With Teeth Tour'),
		-- Year Zero Tour
		('Discipline', 'Year Zero Tour'),
		('Come Back Haunted', 'Year Zero Tour'),
		('Hurt', 'Year Zero Tour'),
		('In This Twilight', 'Year Zero Tour'),
		('Less Than', 'Year Zero Tour'),
		-- Lights in the Sky Tour
		('Discipline', 'Lights in the Sky Tour'),
		('Come Back Haunted', 'Lights in the Sky Tour'),
		('Hurt', 'Lights in the Sky Tour'),
		('Try to Erase Me', 'Lights in the Sky Tour'),
		-- Hesitation Marks Tour
		('Come Back Haunted', 'Hesitation Marks Tour'),
		('Discipline', 'Hesitation Marks Tour'),
		('Head Like a Hole', 'Hesitation Marks Tour'),
		('Closer', 'Hesitation Marks Tour'),
		-- Bad Witch Tour
		('Come Back Haunted', 'Bad Witch Tour'),
		('Discipline', 'Bad Witch Tour'),
		('Hurt', 'Bad Witch Tour'),
		('In This Twilight', 'Bad Witch Tour')
) AS pt(PisteName, TourneeName)
INNER JOIN nine_inch_nails.Piste p ON p.Nom = pt.PisteName
INNER JOIN nine_inch_nails.Tournee t ON t.NomOfficiel = pt.TourneeName;
GO
