-- GENERATED BY AI (2026-02-21) --
USE tp4d5;
GO

-- Insert Parution (Albums, EPs, Singles)
INSERT INTO nine_inch_nails.Parution (Nom, TypeParution, DateSortie, NbVente, NbPiste)
VALUES
	('Pretty Hate Machine', 'album', '1989-10-20', 1500000, 12),
	('Broken', 'album', '1992-09-22', 2000000, 8),
	('The Downward Spiral', 'album', '1994-03-22', 3000000, 13),
	('The Fragile', 'album', '1999-09-21', 2500000, 22),
	('With Teeth', 'album', '2005-05-03', 1800000, 13),
	('Year Zero', 'album', '2007-04-17', 900000, 18),
	('The Slip', 'album', '2008-05-05', 600000, 13),
	('Hesitation Marks', 'album', '2013-09-03', 700000, 13),
	('Bad Witch', 'album', '2018-06-22', 800000, 8),
	('Add Violence', 'ep', '2017-07-21', 300000, 5),
	('Further Down the Spiral', 'ep', '1995-03-22', 400000, 6),
	('Things Falling Apart', 'ep', '2000-12-12', 250000, 8);
GO

-- Insert Piste (Tracks)
INSERT INTO nine_inch_nails.Piste (Nom, TypePiste, DureeSec, AGagneGrammy)
VALUES
	('Head Like a Hole', 'originale', 291, 0),
	('Terrible Lie', 'originale', 289, 0),
	('Down in It', 'originale', 234, 0),
	('Broken', 'originale', 178, 1),
	('Gave Up', 'originale', 360, 1),
	('Pinion', 'originale', 93, 0),
	('Wish', 'originale', 164, 1),
	('Last', 'originale', 291, 0),
	('March of the Pigs', 'originale', 232, 0),
	('Closer', 'originale', 249, 1),
	('The Downward Spiral', 'originale', 282, 0),
	('I Do Not Want This', 'originale', 202, 0),
	('Big Come Down', 'originale', 272, 0),
	('The Perfect Girl', 'originale', 278, 0),
	('Heresy', 'originale', 246, 0),
	('Reptile', 'originale', 373, 0),
	('The Way Out Is Through', 'originale', 285, 0),
	('Into the Void', 'originale', 291, 0),
	('All That Could Have Been', 'originale', 347, 0),
	('Somewhat Damaged', 'originale', 284, 0),
	('The Big Come Down', 'originale', 272, 0),
	('Try to Erase Me', 'originale', 292, 0),
	('The Wretched', 'originale', 453, 0),
	('With Teeth', 'originale', 194, 0),
	('Love Is Not Enough', 'originale', 230, 0),
	('Every Day Is Exactly the Same', 'originale', 205, 0),
	('Only', 'originale', 196, 0),
	('Survivalism', 'originale', 213, 0),
	('Me, I\'m Not', 'originale', 205, 0),
	('Capital G', 'originale', 242, 0),
	('The Good Soldier', 'originale', 227, 0),
	('The Slip', 'originale', 225, 0),
	('Letting Go', 'originale', 190, 0),
	('Echoplex', 'originale', 275, 0),
	('Yet Another Movie', 'originale', 192, 0),
	('All Time Low', 'originale', 229, 0),
	('The Wailing Wall', 'remix', 296, 0),
	('Reptile (Meat Beat Manifesto Mix)', 'remix', 368, 0),
	('I Don\'t Want This', 'remix', 215, 0),
	('Copy of a', 'remix', 278, 0),
	('Beside You in Time', 'live', 385, 0),
	('Discipline', 'originale', 242, 0),
	('Come Back Haunted', 'originale', 243, 0),
	('Hurt', 'originale', 352, 1),
	('In This Twilight', 'originale', 279, 0),
	('Less Than', 'originale', 252, 0);
GO

-- Insert PisteParution (Junction table between Tracks and Releases)
INSERT INTO nine_inch_nails.PisteParution (PisteId, ParutionId)
VALUES
	-- Pretty Hate Machine
	(1, 1), (2, 1), (3, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 1),
	-- Broken
	(4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (37, 2), (38, 2), (39, 2),
	-- The Downward Spiral
	(9, 3), (10, 3), (11, 3), (12, 3), (13, 3), (14, 3), (15, 3), (16, 3), (17, 3), (18, 3), (19, 3), (20, 3), (21, 3),
	-- The Fragile
	(22, 4), (23, 4), (33, 4), (34, 4), (35, 4), (36, 4), (40, 4), (41, 4), (42, 4), (43, 4), (44, 4), (45, 4),
	-- With Teeth
	(24, 5), (25, 5), (26, 5), (27, 5), (28, 5), (29, 5), (30, 5), (31, 5), (32, 5), (33, 5), (34, 5), (35, 5), (36, 5),
	-- Year Zero
	(46, 6), (47, 6), (48, 6), (49, 6), (50, 6);
GO

-- Insert Videoclip (Music Videos)
INSERT INTO nine_inch_nails.Videoclip (NomOfficiel, DateSortie, PisteId)
VALUES
	('Head Like a Hole', '1989-11-15', 1),
	('Terrible Lie', '1990-06-15', 2),
	('Down in It', '1994-03-01', 3),
	('Broken', '1992-10-15', 4),
	('Gave Up', '1992-11-15', 5),
	('Wish', '1992-12-15', 7),
	('Closer', '1994-06-15', 10),
	('March of the Pigs', '1994-07-15', 9),
	('Hurt', '1994-11-15', 44),
	('Perfect Girl', '1995-01-15', 14),
	('The Big Come Down', '1997-09-15', 21),
	('Every Day Is Exactly the Same', '2005-06-15', 26),
	('Only', '2005-08-15', 27),
	('Survivalism', '2007-10-15', 28),
	('Come Back Haunted', '2013-08-20', 42);
GO

-- Insert Tournee (Tours)
INSERT INTO nine_inch_nails.Tournee (NomOfficiel, AnneeDebut, AnneeFin)
VALUES
	('Pretty Hate Machine Tour', 1989, 1990),
	('Broken Tour', 1992, 1993),
	('Self Destruct Tour', 1994, 1995),
	('Against All Authority Tour', 1997, 1999),
	('Fragility Tour', 1999, 2000),
	('With Teeth Tour', 2005, 2006),
	('Year Zero Tour', 2007, 2008),
	('Lights in the Sky Tour', 2008, 2009),
	('Hesitation Marks Tour', 2013, 2014),
	('Bad Witch Tour', 2018, 2019);
GO

-- Insert PisteTournee (Tracks performed on tours) - FIXED with valid PisteId references
INSERT INTO nine_inch_nails.PisteTournee (PisteId, TourneeId)
VALUES
	-- Pretty Hate Machine Tour (TourneeId 1)
	(1, 1), (2, 1), (3, 1),
	-- Broken Tour (TourneeId 2)
	(4, 2), (5, 2), (7, 2), (8, 2),
	-- Self Destruct Tour (TourneeId 3)
	(9, 3), (10, 3), (11, 3), (14, 3), (15, 3),
	-- Against All Authority Tour (TourneeId 4)
	(9, 4), (10, 4), (11, 4), (22, 4), (23, 4),
	-- Fragility Tour (TourneeId 5)
	(22, 5), (23, 5), (1, 5), (44, 5),
	-- With Teeth Tour (TourneeId 6)
	(24, 6), (25, 6), (26, 6), (27, 6), (44, 6),
	-- Year Zero Tour (TourneeId 7)
	(46, 7), (47, 7), (48, 7), (49, 7), (50, 7),
	-- Lights in the Sky Tour (TourneeId 8)
	(46, 8), (47, 8), (48, 8), (22, 8),
	-- Hesitation Marks Tour (TourneeId 9)
	(42, 9), (43, 9), (1, 9), (10, 9),
	-- Bad Witch Tour (TourneeId 10)
	(42, 10), (43, 10), (44, 10), (45, 10);
GO

